### ISSUE TITLE
How to install / build

### ISSUE THREAD

**Issue by homo-iocus** [GameParrot/mcpelauncher-shadersmod#1]
Hi thank you very much for this tool.

I could not figure out how to install this modification to the mcpelauncher. 
Do I need to build the whole mcpelauncher from source while including your mod? Or is there a way to only build your mod while not tampering with the mcpelauncher , which currently is installed via AppImage on my linux machine.

Thanks a lot for any help!

**Comment by onePlaceholder** [comment]
how did you fix this ?
